### ISSUE TITLE
Sort hidden channels in option is deprecated.

### ISSUE THREAD

**Issue by ghost** [Kaiddd/ShowHiddenChannels#4]
The "Sort hidden channels in" setting no longer works, and has been broken for quite a while. Original author also claims is no longer possible to implement, and it dosen't work on this fork either.
I suggest removal of this option if it's unfixable, as it lead me to some confusion, and probably be better for new users.
Edit: whoops re-closed the issue accidentally

**Comment by ghost** [comment]
nvm im dumb

**Comment by Kaiddd** [comment]
I like cats

**Comment by Kaiddd** [comment]
!
